( DEFINE ( PROBLEM BLOCK_REARRANGEMENT0 )
( :DOMAIN BLOCK_REARRANGEMENT )
( :OBJECTS
	A0 A1 - AGENT
	B0 B1 - BLOCK
	R0 R1 R2 R3 - REGION
)
( :INIT
	( FREE-BLOCK )
	( FREE-AGENT A0 )
	( FREE-AGENT A1 )
	( INREGION B0 R0 )
	( INREGION B1 R1 )
	( ISFREE R2 )
	( ISFREE R3 )
	( HANDEMPTY A0 )
	( HANDEMPTY A1 )
)
( :GOAL
	( AND
		( FREE-BLOCK )
		( INREGION B0 R1 )
		( INREGION B1 R0 )
	)
)
)
