( DEFINE ( DOMAIN HUMORO_TABLE )
( :REQUIREMENTS :EQUALITY :NEGATIVE-PRECONDITIONS :CONDITIONAL-EFFECTS :TYPING :UNIVERSAL-PRECONDITIONS )
( :TYPES
	AGENT - SUPERTYPE
	LOCATION - SUPERTYPE
	OBJECT - SUPERTYPE
)
( :CONSTANTS
	TABLE SMALL_SHELF BIG_SHELF - LOCATION
	CUP_RED CUP_GREEN CUP_BLUE CUP_PINK PLATE_PINK PLATE_RED PLATE_GREEN PLATE_BLUE JUG BOWL - OBJECT
)
( :PREDICATES
	( FREE-BLOCK )
	( SELECTING )
	( APPLYING )
	( RESETTING )
	( FREE-AGENT ?AGENT0 - AGENT )
	( BUSY-AGENT ?AGENT0 - AGENT )
	( DONE-AGENT ?AGENT0 - AGENT )
	( ON ?OBJECT0 - OBJECT ?LOCATION1 - LOCATION )
	( OBJECT-AVAILABLE ?OBJECT0 - OBJECT )
	( AGENT-FREE ?AGENT0 - AGENT )
	( AGENT-AT ?AGENT0 - AGENT ?LOCATION1 - LOCATION )
	( AGENT-CARRY ?AGENT0 - AGENT ?OBJECT1 - OBJECT )
	( ACTIVE-MOVE ?AGENT0 - AGENT ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( REQ-NEG-MOVE ?AGENT0 - AGENT ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( ACTIVE-PICK ?AGENT0 - AGENT ?OBJECT1 - OBJECT ?LOCATION2 - LOCATION )
	( REQ-NEG-PICK ?AGENT0 - AGENT ?OBJECT1 - OBJECT ?LOCATION2 - LOCATION )
	( ACTIVE-PLACE ?AGENT0 - AGENT ?OBJECT1 - OBJECT ?LOCATION2 - LOCATION )
	( REQ-NEG-PLACE ?AGENT0 - AGENT ?OBJECT1 - OBJECT ?LOCATION2 - LOCATION )
)
( :ACTION START
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( FREE-BLOCK )
	)
  :EFFECT
	( AND
		( NOT ( FREE-BLOCK ) )
		( SELECTING )
	)
)
( :ACTION APPLY
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( SELECTING )
	)
  :EFFECT
	( AND
		( NOT ( SELECTING ) )
		( APPLYING )
	)
)
( :ACTION RESET
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( APPLYING )
	)
  :EFFECT
	( AND
		( NOT ( APPLYING ) )
		( RESETTING )
	)
)
( :ACTION FINISH
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( RESETTING )
		( FORALL
			( ?AGENT0 - AGENT )
			( FREE-AGENT ?AGENT0 )
		)
	)
  :EFFECT
	( AND
		( NOT ( RESETTING ) )
		( FREE-BLOCK )
	)
)
( :ACTION SELECT-MOVE
  :PARAMETERS ( ?AGENT0 - AGENT ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( SELECTING )
		( FREE-AGENT ?AGENT0 )
		( NOT ( REQ-NEG-MOVE ?AGENT0 ?LOCATION1 ?LOCATION2 ) )
		( AGENT-AT ?AGENT0 ?LOCATION1 )
		( NOT ( AGENT-AT ?AGENT0 ?LOCATION2 ) )
	)
  :EFFECT
	( AND
		( NOT ( FREE-AGENT ?AGENT0 ) )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-MOVE ?AGENT0 ?LOCATION1 ?LOCATION2 )
	)
)
( :ACTION DO-MOVE
  :PARAMETERS ( ?AGENT0 - AGENT ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( APPLYING )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-MOVE ?AGENT0 ?LOCATION1 ?LOCATION2 )
	)
  :EFFECT
	( AND
		( NOT ( BUSY-AGENT ?AGENT0 ) )
		( DONE-AGENT ?AGENT0 )
		( AGENT-AT ?AGENT0 ?LOCATION2 )
		( NOT ( AGENT-AT ?AGENT0 ?LOCATION1 ) )
	)
)
( :ACTION END-MOVE
  :PARAMETERS ( ?AGENT0 - AGENT ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( RESETTING )
		( DONE-AGENT ?AGENT0 )
		( ACTIVE-MOVE ?AGENT0 ?LOCATION1 ?LOCATION2 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-AGENT ?AGENT0 ) )
		( FREE-AGENT ?AGENT0 )
		( NOT ( ACTIVE-MOVE ?AGENT0 ?LOCATION1 ?LOCATION2 ) )
	)
)
( :ACTION SELECT-PICK
  :PARAMETERS ( ?AGENT0 - AGENT ?OBJECT1 - OBJECT ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( SELECTING )
		( FREE-AGENT ?AGENT0 )
		( NOT ( REQ-NEG-PICK ?AGENT0 ?OBJECT1 ?LOCATION2 ) )
		( AGENT-AT ?AGENT0 ?LOCATION2 )
		( ON ?OBJECT1 ?LOCATION2 )
		( OBJECT-AVAILABLE ?OBJECT1 )
		( AGENT-FREE ?AGENT0 )
		( NOT ( ACTIVE-PICK ?AGENT0 ?OBJECT1 ?LOCATION2 ) )
	)
  :EFFECT
	( AND
		( NOT ( FREE-AGENT ?AGENT0 ) )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-PICK ?AGENT0 ?OBJECT1 ?LOCATION2 )
		( REQ-NEG-PICK ?AGENT0 ?OBJECT1 ?LOCATION2 )
	)
)
( :ACTION DO-PICK
  :PARAMETERS ( ?AGENT0 - AGENT ?OBJECT1 - OBJECT ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( APPLYING )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-PICK ?AGENT0 ?OBJECT1 ?LOCATION2 )
	)
  :EFFECT
	( AND
		( NOT ( BUSY-AGENT ?AGENT0 ) )
		( DONE-AGENT ?AGENT0 )
		( NOT ( ON ?OBJECT1 ?LOCATION2 ) )
		( NOT ( OBJECT-AVAILABLE ?OBJECT1 ) )
		( NOT ( AGENT-FREE ?AGENT0 ) )
		( AGENT-CARRY ?AGENT0 ?OBJECT1 )
		( AGENT-AT ?AGENT0 ?LOCATION2 )
	)
)
( :ACTION END-PICK
  :PARAMETERS ( ?AGENT0 - AGENT ?OBJECT1 - OBJECT ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( RESETTING )
		( DONE-AGENT ?AGENT0 )
		( ACTIVE-PICK ?AGENT0 ?OBJECT1 ?LOCATION2 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-AGENT ?AGENT0 ) )
		( FREE-AGENT ?AGENT0 )
		( NOT ( ACTIVE-PICK ?AGENT0 ?OBJECT1 ?LOCATION2 ) )
		( NOT ( REQ-NEG-PICK ?AGENT0 ?OBJECT1 ?LOCATION2 ) )
	)
)
( :ACTION SELECT-PLACE
  :PARAMETERS ( ?AGENT0 - AGENT ?OBJECT1 - OBJECT ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( SELECTING )
		( FREE-AGENT ?AGENT0 )
		( NOT ( REQ-NEG-PLACE ?AGENT0 ?OBJECT1 ?LOCATION2 ) )
		( AGENT-AT ?AGENT0 ?LOCATION2 )
		( AGENT-CARRY ?AGENT0 ?OBJECT1 )
	)
  :EFFECT
	( AND
		( NOT ( FREE-AGENT ?AGENT0 ) )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-PLACE ?AGENT0 ?OBJECT1 ?LOCATION2 )
	)
)
( :ACTION DO-PLACE
  :PARAMETERS ( ?AGENT0 - AGENT ?OBJECT1 - OBJECT ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( APPLYING )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-PLACE ?AGENT0 ?OBJECT1 ?LOCATION2 )
	)
  :EFFECT
	( AND
		( NOT ( BUSY-AGENT ?AGENT0 ) )
		( DONE-AGENT ?AGENT0 )
		( ON ?OBJECT1 ?LOCATION2 )
		( OBJECT-AVAILABLE ?OBJECT1 )
		( AGENT-FREE ?AGENT0 )
		( NOT ( AGENT-CARRY ?AGENT0 ?OBJECT1 ) )
		( AGENT-AT ?AGENT0 ?LOCATION2 )
	)
)
( :ACTION END-PLACE
  :PARAMETERS ( ?AGENT0 - AGENT ?OBJECT1 - OBJECT ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( RESETTING )
		( DONE-AGENT ?AGENT0 )
		( ACTIVE-PLACE ?AGENT0 ?OBJECT1 ?LOCATION2 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-AGENT ?AGENT0 ) )
		( FREE-AGENT ?AGENT0 )
		( NOT ( ACTIVE-PLACE ?AGENT0 ?OBJECT1 ?LOCATION2 ) )
	)
)
)
