( DEFINE ( DOMAIN HUMORO_TABLE )
( :REQUIREMENTS :EQUALITY :NEGATIVE-PRECONDITIONS :CONDITIONAL-EFFECTS )
( :PREDICATES
    ( AGENT ?AGENT0 )
    ( OBJECT ?OBJECT1 )
    ( LOCATION ?LOCATION1 )
	( FREE-BLOCK )
	( SELECTING )
	( APPLYING )
	( RESETTING )
	( FREE-AGENT ?AGENT0 )
	( BUSY-AGENT ?AGENT0 )
	( DONE-AGENT ?AGENT0 )
	( ON ?OBJECT1 ?LOCATION1 )
	( OBJECT-AVAILABLE ?OBJECT1 )
	( AGENT-FREE ?AGENT0 )
	( AGENT-AT ?AGENT0 ?LOCATION1 )
	( AGENT-CARRY ?AGENT0 ?OBJECT1 )
	( ACTIVE-MOVE ?AGENT0 ?LOCATION1 ?LOCATION2 )
	( REQ-NEG-MOVE ?AGENT0 ?LOCATION1 ?LOCATION2 )
	( ACTIVE-PICK ?AGENT0 ?OBJECT1 ?LOCATION2 )
	( REQ-NEG-PICK ?AGENT0 ?OBJECT1 ?LOCATION2 )
	( ACTIVE-PLACE ?AGENT0 ?OBJECT1 ?LOCATION2 )
	( REQ-NEG-PLACE ?AGENT0 ?OBJECT1 ?LOCATION2 )
)
( :ACTION START
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( FREE-BLOCK )
	)
  :EFFECT
	( AND
		( NOT ( FREE-BLOCK ) )
		( SELECTING )
	)
)
( :ACTION APPLY
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( SELECTING )
	)
  :EFFECT
	( AND
		( NOT ( SELECTING ) )
		( APPLYING )
	)
)
( :ACTION RESET
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( APPLYING )
	)
  :EFFECT
	( AND
		( NOT ( APPLYING ) )
		( RESETTING )
	)
)
( :ACTION FINISH
  :PARAMETERS ( ?AGENT0 )
  :PRECONDITION
	( AND
	    ( AGENT ?AGENT0 )
		( RESETTING )
		( FREE-AGENT ?AGENT0)
	)
  :EFFECT
	( AND
		( NOT ( RESETTING ) )
		( FREE-BLOCK )
	)
)
( :ACTION SELECT-MOVE
  :PARAMETERS ( ?AGENT0 ?LOCATION1 ?LOCATION2 )
  :PRECONDITION
	( AND
	    ( AGENT ?AGENT0 )
	    ( LOCATION ?LOCATION1 )
	    ( LOCATION ?LOCATION2 )
		( SELECTING )
		( FREE-AGENT ?AGENT0 )
		( NOT ( REQ-NEG-MOVE ?AGENT0 ?LOCATION1 ?LOCATION2 ) )
		( AGENT-AT ?AGENT0 ?LOCATION1 )
		( NOT ( AGENT-AT ?AGENT0 ?LOCATION2 ) )
	)
  :EFFECT
	( AND
		( NOT ( FREE-AGENT ?AGENT0 ) )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-MOVE ?AGENT0 ?LOCATION1 ?LOCATION2 )
	)
)
( :ACTION DO-MOVE
  :PARAMETERS ( ?AGENT0 ?LOCATION1 ?LOCATION2 )
  :PRECONDITION
	( AND
	    ( AGENT ?AGENT0 )
	    ( LOCATION ?LOCATION1 )
	    ( LOCATION ?LOCATION2 )
		( APPLYING )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-MOVE ?AGENT0 ?LOCATION1 ?LOCATION2 )
	)
  :EFFECT
	( AND
		( NOT ( BUSY-AGENT ?AGENT0 ) )
		( DONE-AGENT ?AGENT0 )
		( AGENT-AT ?AGENT0 ?LOCATION2 )
		( NOT ( AGENT-AT ?AGENT0 ?LOCATION1 ) )
	)
)
( :ACTION END-MOVE
  :PARAMETERS ( ?AGENT0 ?LOCATION1 ?LOCATION2 )
  :PRECONDITION
	( AND
	    ( AGENT ?AGENT0 )
	    ( LOCATION ?LOCATION1 )
	    ( LOCATION ?LOCATION2 )
		( RESETTING )
		( DONE-AGENT ?AGENT0 )
		( ACTIVE-MOVE ?AGENT0 ?LOCATION1 ?LOCATION2 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-AGENT ?AGENT0 ) )
		( FREE-AGENT ?AGENT0 )
		( NOT ( ACTIVE-MOVE ?AGENT0 ?LOCATION1 ?LOCATION2 ) )
	)
)
( :ACTION SELECT-PICK
  :PARAMETERS ( ?AGENT0 ?OBJECT1 ?LOCATION2 )
  :PRECONDITION
	( AND
	    ( AGENT ?AGENT0 )
	    ( OBJECT ?OBJECT1 )
	    ( LOCATION ?LOCATION2 )
		( SELECTING )
		( FREE-AGENT ?AGENT0 )
		( NOT ( REQ-NEG-PICK ?AGENT0 ?OBJECT1 ?LOCATION2 ) )
		( AGENT-AT ?AGENT0 ?LOCATION2 )
		( ON ?OBJECT1 ?LOCATION2 )
		( OBJECT-AVAILABLE ?OBJECT1 )
		( AGENT-FREE ?AGENT0 )
		( NOT ( ACTIVE-PICK ?AGENT0 ?OBJECT1 ?LOCATION2 ) )
	)
  :EFFECT
	( AND
		( NOT ( FREE-AGENT ?AGENT0 ) )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-PICK ?AGENT0 ?OBJECT1 ?LOCATION2 )
		( REQ-NEG-PICK ?AGENT0 ?OBJECT1 ?LOCATION2 )
	)
)
( :ACTION DO-PICK
  :PARAMETERS ( ?AGENT0 ?OBJECT1 ?LOCATION2 )
  :PRECONDITION
	( AND
	    ( AGENT ?AGENT0 )
	    ( OBJECT ?OBJECT1 )
	    ( LOCATION ?LOCATION2 )
		( APPLYING )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-PICK ?AGENT0 ?OBJECT1 ?LOCATION2 )
	)
  :EFFECT
	( AND
		( NOT ( BUSY-AGENT ?AGENT0 ) )
		( DONE-AGENT ?AGENT0 )
		( NOT ( ON ?OBJECT1 ?LOCATION2 ) )
		( NOT ( OBJECT-AVAILABLE ?OBJECT1 ) )
		( NOT ( AGENT-FREE ?AGENT0 ) )
		( AGENT-CARRY ?AGENT0 ?OBJECT1 )
		( AGENT-AT ?AGENT0 ?LOCATION2 )
	)
)
( :ACTION END-PICK
  :PARAMETERS ( ?AGENT0 ?OBJECT1 ?LOCATION2 )
  :PRECONDITION
	( AND
	    ( AGENT ?AGENT0 )
	    ( OBJECT ?OBJECT1 )
	    ( LOCATION ?LOCATION2 )
		( RESETTING )
		( DONE-AGENT ?AGENT0 )
		( ACTIVE-PICK ?AGENT0 ?OBJECT1 ?LOCATION2 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-AGENT ?AGENT0 ) )
		( FREE-AGENT ?AGENT0 )
		( NOT ( ACTIVE-PICK ?AGENT0 ?OBJECT1 ?LOCATION2 ) )
		( NOT ( REQ-NEG-PICK ?AGENT0 ?OBJECT1 ?LOCATION2 ) )
	)
)
( :ACTION SELECT-PLACE
  :PARAMETERS ( ?AGENT0 ?OBJECT1 ?LOCATION2 )
  :PRECONDITION
	( AND
	    ( AGENT ?AGENT0 )
	    ( OBJECT ?OBJECT1 )
	    ( LOCATION ?LOCATION2 )
		( SELECTING )
		( FREE-AGENT ?AGENT0 )
		( NOT ( REQ-NEG-PLACE ?AGENT0 ?OBJECT1 ?LOCATION2 ) )
		( AGENT-AT ?AGENT0 ?LOCATION2 )
		( AGENT-CARRY ?AGENT0 ?OBJECT1 )
	)
  :EFFECT
	( AND
		( NOT ( FREE-AGENT ?AGENT0 ) )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-PLACE ?AGENT0 ?OBJECT1 ?LOCATION2 )
	)
)
( :ACTION DO-PLACE
  :PARAMETERS ( ?AGENT0 ?OBJECT1 ?LOCATION2 )
  :PRECONDITION
	( AND
	    ( AGENT ?AGENT0 )
	    ( OBJECT ?OBJECT1 )
	    ( LOCATION ?LOCATION2 )
		( APPLYING )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-PLACE ?AGENT0 ?OBJECT1 ?LOCATION2 )
	)
  :EFFECT
	( AND
		( NOT ( BUSY-AGENT ?AGENT0 ) )
		( DONE-AGENT ?AGENT0 )
		( ON ?OBJECT1 ?LOCATION2 )
		( OBJECT-AVAILABLE ?OBJECT1 )
		( AGENT-FREE ?AGENT0 )
		( NOT ( AGENT-CARRY ?AGENT0 ?OBJECT1 ) )
		( AGENT-AT ?AGENT0 ?LOCATION2 )
	)
)
( :ACTION END-PLACE
  :PARAMETERS ( ?AGENT0 ?OBJECT1 ?LOCATION2 )
  :PRECONDITION
	( AND
	    ( AGENT ?AGENT0 )
	    ( OBJECT ?OBJECT1 )
	    ( LOCATION ?LOCATION2 )
		( RESETTING )
		( DONE-AGENT ?AGENT0 )
		( ACTIVE-PLACE ?AGENT0 ?OBJECT1 ?LOCATION2 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-AGENT ?AGENT0 ) )
		( FREE-AGENT ?AGENT0 )
		( NOT ( ACTIVE-PLACE ?AGENT0 ?OBJECT1 ?LOCATION2 ) )
	)
)
)
