( DEFINE ( DOMAIN TABLEMOVER )
( :REQUIREMENTS :EQUALITY :NEGATIVE-PRECONDITIONS :CONDITIONAL-EFFECTS :TYPING :UNIVERSAL-PRECONDITIONS )
( :TYPES
	LOCATABLE - OBJECT
	AGENT - LOCATABLE
	BLOCK - LOCATABLE
	TABLE - LOCATABLE
	SIDE - OBJECT
	SIDE0 - SIDE
	ROOM - OBJECT
)
( :CONSTANTS
	TABLE0 - TABLE
)
( :PREDICATES
	( FREE-BLOCK )
	( SELECTING )
	( APPLYING )
	( RESETTING )
	( FREE-AGENT ?AGENT0 - AGENT )
	( BUSY-AGENT ?AGENT0 - AGENT )
	( DONE-AGENT ?AGENT0 - AGENT )
	( ON-TABLE ?BLOCK0 - BLOCK ?TABLE1 - TABLE )
	( ON-FLOOR ?BLOCK0 - BLOCK )
	( DOWN ?SIDE0 - SIDE )
	( UP ?SIDE0 - SIDE )
	( CLEAR ?SIDE0 - SIDE )
	( AT-SIDE ?AGENT0 - AGENT ?SIDE1 - SIDE )
	( LIFTING ?AGENT0 - AGENT ?SIDE1 - SIDE )
	( INROOM ?LOCATABLE0 - LOCATABLE ?ROOM1 - ROOM )
	( AVAILABLE ?AGENT0 - AGENT )
	( HANDEMPTY ?AGENT0 - AGENT )
	( HOLDING ?AGENT0 - AGENT ?BLOCK1 - BLOCK )
	( CONNECTED ?ROOM0 - ROOM ?ROOM1 - ROOM )
	( ACTIVE-PICKUP-FLOOR ?AGENT0 - AGENT ?BLOCK1 - BLOCK ?ROOM2 - ROOM )
	( REQ-NEG-PICKUP-FLOOR ?AGENT0 - AGENT ?BLOCK1 - BLOCK ?ROOM2 - ROOM )
	( ACTIVE-PUTDOWN-FLOOR ?AGENT0 - AGENT ?BLOCK1 - BLOCK ?ROOM2 - ROOM )
	( REQ-NEG-PUTDOWN-FLOOR ?AGENT0 - AGENT ?BLOCK1 - BLOCK ?ROOM2 - ROOM )
	( ACTIVE-MOVE-AGENT ?AGENT0 - AGENT ?ROOM1 - ROOM ?ROOM2 - ROOM )
	( REQ-NEG-MOVE-AGENT ?AGENT0 - AGENT ?ROOM1 - ROOM ?ROOM2 - ROOM )
	( ACTIVE-PICKUP-TABLE-0 ?AGENT0 - AGENT ?BLOCK1 - BLOCK ?ROOM2 - ROOM )
	( REQ-NEG-PICKUP-TABLE-0 ?AGENT0 - AGENT ?BLOCK1 - BLOCK ?ROOM2 - ROOM )
	( ACTIVE-PUTDOWN-TABLE-0 ?AGENT0 - AGENT ?BLOCK1 - BLOCK ?ROOM2 - ROOM )
	( REQ-NEG-PUTDOWN-TABLE-0 ?AGENT0 - AGENT ?BLOCK1 - BLOCK ?ROOM2 - ROOM )
	( ACTIVE-TO-TABLE-0 ?AGENT0 - AGENT ?ROOM1 - ROOM ?SIDE02 - SIDE0 )
	( REQ-NEG-TO-TABLE-0 ?AGENT0 - AGENT ?ROOM1 - ROOM ?SIDE02 - SIDE0 )
	( ACTIVE-LEAVE-TABLE-0 ?AGENT0 - AGENT ?SIDE01 - SIDE0 )
	( REQ-NEG-LEAVE-TABLE-0 ?AGENT0 - AGENT ?SIDE01 - SIDE0 )
	( ACTIVE-MOVE-TABLE-0 ?AGENT0 - AGENT ?ROOM1 - ROOM ?ROOM2 - ROOM ?SIDE03 - SIDE0 )
	( REQ-NEG-MOVE-TABLE-0 ?AGENT0 - AGENT ?ROOM1 - ROOM ?ROOM2 - ROOM ?SIDE03 - SIDE0 )
	( ACTIVE-LIFT-SIDE-0 ?AGENT0 - AGENT ?SIDE01 - SIDE0 )
	( REQ-NEG-LIFT-SIDE-0 ?AGENT0 - AGENT ?SIDE01 - SIDE0 )
	( ACTIVE-LOWER-SIDE-0 ?AGENT0 - AGENT ?SIDE01 - SIDE0 )
	( REQ-NEG-LOWER-SIDE-0 ?AGENT0 - AGENT ?SIDE01 - SIDE0 )
)
( :ACTION START
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( FREE-BLOCK )
	)
  :EFFECT
	( AND
		( NOT ( FREE-BLOCK ) )
		( SELECTING )
	)
)
( :ACTION APPLY
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( SELECTING )
	)
  :EFFECT
	( AND
		( NOT ( SELECTING ) )
		( APPLYING )
	)
)
( :ACTION RESET
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( APPLYING )
	)
  :EFFECT
	( AND
		( NOT ( APPLYING ) )
		( RESETTING )
	)
)
( :ACTION FINISH
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( RESETTING )
		( FORALL
			( ?AGENT0 - AGENT )
			( FREE-AGENT ?AGENT0 )
		)
	)
  :EFFECT
	( AND
		( NOT ( RESETTING ) )
		( FREE-BLOCK )
	)
)
( :ACTION SELECT-PICKUP-FLOOR
  :PARAMETERS ( ?AGENT0 - AGENT ?BLOCK1 - BLOCK ?ROOM2 - ROOM )
  :PRECONDITION
	( AND
		( SELECTING )
		( FREE-AGENT ?AGENT0 )
		( NOT ( REQ-NEG-PICKUP-FLOOR ?AGENT0 ?BLOCK1 ?ROOM2 ) )
		( ON-FLOOR ?BLOCK1 )
		( INROOM ?AGENT0 ?ROOM2 )
		( INROOM ?BLOCK1 ?ROOM2 )
		( AVAILABLE ?AGENT0 )
		( HANDEMPTY ?AGENT0 )
		( FORALL
			( ?AGENT3 - AGENT )
			( AND
				( NOT ( ACTIVE-PICKUP-FLOOR ?AGENT3 ?BLOCK1 ?ROOM2 ) )
			)
		)
	)
  :EFFECT
	( AND
		( NOT ( FREE-AGENT ?AGENT0 ) )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-PICKUP-FLOOR ?AGENT0 ?BLOCK1 ?ROOM2 )
		( FORALL
			( ?AGENT3 - AGENT )
			( AND
				( REQ-NEG-PICKUP-FLOOR ?AGENT3 ?BLOCK1 ?ROOM2 )
			)
		)
	)
)
( :ACTION DO-PICKUP-FLOOR
  :PARAMETERS ( ?AGENT0 - AGENT ?BLOCK1 - BLOCK ?ROOM2 - ROOM )
  :PRECONDITION
	( AND
		( APPLYING )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-PICKUP-FLOOR ?AGENT0 ?BLOCK1 ?ROOM2 )
	)
  :EFFECT
	( AND
		( NOT ( BUSY-AGENT ?AGENT0 ) )
		( DONE-AGENT ?AGENT0 )
		( NOT ( ON-FLOOR ?BLOCK1 ) )
		( NOT ( INROOM ?BLOCK1 ?ROOM2 ) )
		( NOT ( HANDEMPTY ?AGENT0 ) )
		( HOLDING ?AGENT0 ?BLOCK1 )
	)
)
( :ACTION END-PICKUP-FLOOR
  :PARAMETERS ( ?AGENT0 - AGENT ?BLOCK1 - BLOCK ?ROOM2 - ROOM )
  :PRECONDITION
	( AND
		( RESETTING )
		( DONE-AGENT ?AGENT0 )
		( ACTIVE-PICKUP-FLOOR ?AGENT0 ?BLOCK1 ?ROOM2 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-AGENT ?AGENT0 ) )
		( FREE-AGENT ?AGENT0 )
		( NOT ( ACTIVE-PICKUP-FLOOR ?AGENT0 ?BLOCK1 ?ROOM2 ) )
		( FORALL
			( ?AGENT3 - AGENT )
			( AND
				( NOT ( REQ-NEG-PICKUP-FLOOR ?AGENT3 ?BLOCK1 ?ROOM2 ) )
			)
		)
	)
)
( :ACTION SELECT-PUTDOWN-FLOOR
  :PARAMETERS ( ?AGENT0 - AGENT ?BLOCK1 - BLOCK ?ROOM2 - ROOM )
  :PRECONDITION
	( AND
		( SELECTING )
		( FREE-AGENT ?AGENT0 )
		( NOT ( REQ-NEG-PUTDOWN-FLOOR ?AGENT0 ?BLOCK1 ?ROOM2 ) )
		( AVAILABLE ?AGENT0 )
		( INROOM ?AGENT0 ?ROOM2 )
		( HOLDING ?AGENT0 ?BLOCK1 )
	)
  :EFFECT
	( AND
		( NOT ( FREE-AGENT ?AGENT0 ) )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-PUTDOWN-FLOOR ?AGENT0 ?BLOCK1 ?ROOM2 )
	)
)
( :ACTION DO-PUTDOWN-FLOOR
  :PARAMETERS ( ?AGENT0 - AGENT ?BLOCK1 - BLOCK ?ROOM2 - ROOM )
  :PRECONDITION
	( AND
		( APPLYING )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-PUTDOWN-FLOOR ?AGENT0 ?BLOCK1 ?ROOM2 )
	)
  :EFFECT
	( AND
		( NOT ( BUSY-AGENT ?AGENT0 ) )
		( DONE-AGENT ?AGENT0 )
		( ON-FLOOR ?BLOCK1 )
		( INROOM ?BLOCK1 ?ROOM2 )
		( HANDEMPTY ?AGENT0 )
		( NOT ( HOLDING ?AGENT0 ?BLOCK1 ) )
	)
)
( :ACTION END-PUTDOWN-FLOOR
  :PARAMETERS ( ?AGENT0 - AGENT ?BLOCK1 - BLOCK ?ROOM2 - ROOM )
  :PRECONDITION
	( AND
		( RESETTING )
		( DONE-AGENT ?AGENT0 )
		( ACTIVE-PUTDOWN-FLOOR ?AGENT0 ?BLOCK1 ?ROOM2 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-AGENT ?AGENT0 ) )
		( FREE-AGENT ?AGENT0 )
		( NOT ( ACTIVE-PUTDOWN-FLOOR ?AGENT0 ?BLOCK1 ?ROOM2 ) )
	)
)
( :ACTION SELECT-MOVE-AGENT
  :PARAMETERS ( ?AGENT0 - AGENT ?ROOM1 - ROOM ?ROOM2 - ROOM )
  :PRECONDITION
	( AND
		( SELECTING )
		( FREE-AGENT ?AGENT0 )
		( NOT ( REQ-NEG-MOVE-AGENT ?AGENT0 ?ROOM1 ?ROOM2 ) )
		( AVAILABLE ?AGENT0 )
		( INROOM ?AGENT0 ?ROOM1 )
		( CONNECTED ?ROOM1 ?ROOM2 )
	)
  :EFFECT
	( AND
		( NOT ( FREE-AGENT ?AGENT0 ) )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-MOVE-AGENT ?AGENT0 ?ROOM1 ?ROOM2 )
	)
)
( :ACTION DO-MOVE-AGENT
  :PARAMETERS ( ?AGENT0 - AGENT ?ROOM1 - ROOM ?ROOM2 - ROOM )
  :PRECONDITION
	( AND
		( APPLYING )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-MOVE-AGENT ?AGENT0 ?ROOM1 ?ROOM2 )
	)
  :EFFECT
	( AND
		( NOT ( BUSY-AGENT ?AGENT0 ) )
		( DONE-AGENT ?AGENT0 )
		( NOT ( INROOM ?AGENT0 ?ROOM1 ) )
		( INROOM ?AGENT0 ?ROOM2 )
	)
)
( :ACTION END-MOVE-AGENT
  :PARAMETERS ( ?AGENT0 - AGENT ?ROOM1 - ROOM ?ROOM2 - ROOM )
  :PRECONDITION
	( AND
		( RESETTING )
		( DONE-AGENT ?AGENT0 )
		( ACTIVE-MOVE-AGENT ?AGENT0 ?ROOM1 ?ROOM2 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-AGENT ?AGENT0 ) )
		( FREE-AGENT ?AGENT0 )
		( NOT ( ACTIVE-MOVE-AGENT ?AGENT0 ?ROOM1 ?ROOM2 ) )
	)
)
( :ACTION SELECT-PICKUP-TABLE-0
  :PARAMETERS ( ?AGENT0 - AGENT ?BLOCK1 - BLOCK ?ROOM2 - ROOM )
  :PRECONDITION
	( AND
		( SELECTING )
		( FREE-AGENT ?AGENT0 )
		( NOT ( REQ-NEG-PICKUP-TABLE-0 ?AGENT0 ?BLOCK1 ?ROOM2 ) )
		( ON-TABLE ?BLOCK1 TABLE0 )
		( INROOM ?AGENT0 ?ROOM2 )
		( INROOM TABLE0 ?ROOM2 )
		( AVAILABLE ?AGENT0 )
		( HANDEMPTY ?AGENT0 )
		( FORALL
			( ?AGENT3 - AGENT )
			( AND
				( NOT ( ACTIVE-PICKUP-TABLE-0 ?AGENT3 ?BLOCK1 ?ROOM2 ) )
			)
		)
	)
  :EFFECT
	( AND
		( NOT ( FREE-AGENT ?AGENT0 ) )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-PICKUP-TABLE-0 ?AGENT0 ?BLOCK1 ?ROOM2 )
		( FORALL
			( ?AGENT3 - AGENT )
			( AND
				( REQ-NEG-PICKUP-TABLE-0 ?AGENT3 ?BLOCK1 ?ROOM2 )
			)
		)
	)
)
( :ACTION DO-PICKUP-TABLE-0
  :PARAMETERS ( ?AGENT0 - AGENT ?BLOCK1 - BLOCK ?ROOM2 - ROOM )
  :PRECONDITION
	( AND
		( APPLYING )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-PICKUP-TABLE-0 ?AGENT0 ?BLOCK1 ?ROOM2 )
	)
  :EFFECT
	( AND
		( NOT ( BUSY-AGENT ?AGENT0 ) )
		( DONE-AGENT ?AGENT0 )
		( NOT ( ON-TABLE ?BLOCK1 TABLE0 ) )
		( NOT ( HANDEMPTY ?AGENT0 ) )
		( HOLDING ?AGENT0 ?BLOCK1 )
	)
)
( :ACTION END-PICKUP-TABLE-0
  :PARAMETERS ( ?AGENT0 - AGENT ?BLOCK1 - BLOCK ?ROOM2 - ROOM )
  :PRECONDITION
	( AND
		( RESETTING )
		( DONE-AGENT ?AGENT0 )
		( ACTIVE-PICKUP-TABLE-0 ?AGENT0 ?BLOCK1 ?ROOM2 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-AGENT ?AGENT0 ) )
		( FREE-AGENT ?AGENT0 )
		( NOT ( ACTIVE-PICKUP-TABLE-0 ?AGENT0 ?BLOCK1 ?ROOM2 ) )
		( FORALL
			( ?AGENT3 - AGENT )
			( AND
				( NOT ( REQ-NEG-PICKUP-TABLE-0 ?AGENT3 ?BLOCK1 ?ROOM2 ) )
			)
		)
	)
)
( :ACTION SELECT-PUTDOWN-TABLE-0
  :PARAMETERS ( ?AGENT0 - AGENT ?BLOCK1 - BLOCK ?ROOM2 - ROOM )
  :PRECONDITION
	( AND
		( SELECTING )
		( FREE-AGENT ?AGENT0 )
		( NOT ( REQ-NEG-PUTDOWN-TABLE-0 ?AGENT0 ?BLOCK1 ?ROOM2 ) )
		( INROOM ?AGENT0 ?ROOM2 )
		( INROOM TABLE0 ?ROOM2 )
		( AVAILABLE ?AGENT0 )
		( HOLDING ?AGENT0 ?BLOCK1 )
		( FORALL
			( ?SIDE03 - SIDE0 )
			( AND
				( DOWN ?SIDE03 )
			)
		)
		( FORALL
			( ?AGENT3 - AGENT ?SIDE04 - SIDE0 )
			( AND
				( NOT ( ACTIVE-LIFT-SIDE-0 ?AGENT3 ?SIDE04 ) )
			)
		)
	)
  :EFFECT
	( AND
		( NOT ( FREE-AGENT ?AGENT0 ) )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-PUTDOWN-TABLE-0 ?AGENT0 ?BLOCK1 ?ROOM2 )
		( FORALL
			( ?AGENT3 - AGENT ?SIDE04 - SIDE0 )
			( AND
				( REQ-NEG-LIFT-SIDE-0 ?AGENT3 ?SIDE04 )
			)
		)
	)
)
( :ACTION DO-PUTDOWN-TABLE-0
  :PARAMETERS ( ?AGENT0 - AGENT ?BLOCK1 - BLOCK ?ROOM2 - ROOM )
  :PRECONDITION
	( AND
		( APPLYING )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-PUTDOWN-TABLE-0 ?AGENT0 ?BLOCK1 ?ROOM2 )
	)
  :EFFECT
	( AND
		( NOT ( BUSY-AGENT ?AGENT0 ) )
		( DONE-AGENT ?AGENT0 )
		( ON-TABLE ?BLOCK1 TABLE0 )
		( HANDEMPTY ?AGENT0 )
		( NOT ( HOLDING ?AGENT0 ?BLOCK1 ) )
	)
)
( :ACTION END-PUTDOWN-TABLE-0
  :PARAMETERS ( ?AGENT0 - AGENT ?BLOCK1 - BLOCK ?ROOM2 - ROOM )
  :PRECONDITION
	( AND
		( RESETTING )
		( DONE-AGENT ?AGENT0 )
		( ACTIVE-PUTDOWN-TABLE-0 ?AGENT0 ?BLOCK1 ?ROOM2 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-AGENT ?AGENT0 ) )
		( FREE-AGENT ?AGENT0 )
		( NOT ( ACTIVE-PUTDOWN-TABLE-0 ?AGENT0 ?BLOCK1 ?ROOM2 ) )
		( FORALL
			( ?AGENT3 - AGENT ?SIDE04 - SIDE0 )
			( AND
				( NOT ( REQ-NEG-LIFT-SIDE-0 ?AGENT3 ?SIDE04 ) )
			)
		)
	)
)
( :ACTION SELECT-TO-TABLE-0
  :PARAMETERS ( ?AGENT0 - AGENT ?ROOM1 - ROOM ?SIDE02 - SIDE0 )
  :PRECONDITION
	( AND
		( SELECTING )
		( FREE-AGENT ?AGENT0 )
		( NOT ( REQ-NEG-TO-TABLE-0 ?AGENT0 ?ROOM1 ?SIDE02 ) )
		( CLEAR ?SIDE02 )
		( INROOM ?AGENT0 ?ROOM1 )
		( INROOM TABLE0 ?ROOM1 )
		( AVAILABLE ?AGENT0 )
		( FORALL
			( ?AGENT3 - AGENT )
			( AND
				( NOT ( ACTIVE-TO-TABLE-0 ?AGENT3 ?ROOM1 ?SIDE02 ) )
			)
		)
	)
  :EFFECT
	( AND
		( NOT ( FREE-AGENT ?AGENT0 ) )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-TO-TABLE-0 ?AGENT0 ?ROOM1 ?SIDE02 )
		( FORALL
			( ?AGENT3 - AGENT )
			( AND
				( REQ-NEG-TO-TABLE-0 ?AGENT3 ?ROOM1 ?SIDE02 )
			)
		)
	)
)
( :ACTION DO-TO-TABLE-0
  :PARAMETERS ( ?AGENT0 - AGENT ?ROOM1 - ROOM ?SIDE02 - SIDE0 )
  :PRECONDITION
	( AND
		( APPLYING )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-TO-TABLE-0 ?AGENT0 ?ROOM1 ?SIDE02 )
	)
  :EFFECT
	( AND
		( NOT ( BUSY-AGENT ?AGENT0 ) )
		( DONE-AGENT ?AGENT0 )
		( NOT ( CLEAR ?SIDE02 ) )
		( AT-SIDE ?AGENT0 ?SIDE02 )
		( NOT ( AVAILABLE ?AGENT0 ) )
	)
)
( :ACTION END-TO-TABLE-0
  :PARAMETERS ( ?AGENT0 - AGENT ?ROOM1 - ROOM ?SIDE02 - SIDE0 )
  :PRECONDITION
	( AND
		( RESETTING )
		( DONE-AGENT ?AGENT0 )
		( ACTIVE-TO-TABLE-0 ?AGENT0 ?ROOM1 ?SIDE02 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-AGENT ?AGENT0 ) )
		( FREE-AGENT ?AGENT0 )
		( NOT ( ACTIVE-TO-TABLE-0 ?AGENT0 ?ROOM1 ?SIDE02 ) )
		( FORALL
			( ?AGENT3 - AGENT )
			( AND
				( NOT ( REQ-NEG-TO-TABLE-0 ?AGENT3 ?ROOM1 ?SIDE02 ) )
			)
		)
	)
)
( :ACTION SELECT-LEAVE-TABLE-0
  :PARAMETERS ( ?AGENT0 - AGENT ?SIDE01 - SIDE0 )
  :PRECONDITION
	( AND
		( SELECTING )
		( FREE-AGENT ?AGENT0 )
		( NOT ( REQ-NEG-LEAVE-TABLE-0 ?AGENT0 ?SIDE01 ) )
		( AT-SIDE ?AGENT0 ?SIDE01 )
		( NOT ( LIFTING ?AGENT0 ?SIDE01 ) )
	)
  :EFFECT
	( AND
		( NOT ( FREE-AGENT ?AGENT0 ) )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-LEAVE-TABLE-0 ?AGENT0 ?SIDE01 )
	)
)
( :ACTION DO-LEAVE-TABLE-0
  :PARAMETERS ( ?AGENT0 - AGENT ?SIDE01 - SIDE0 )
  :PRECONDITION
	( AND
		( APPLYING )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-LEAVE-TABLE-0 ?AGENT0 ?SIDE01 )
	)
  :EFFECT
	( AND
		( NOT ( BUSY-AGENT ?AGENT0 ) )
		( DONE-AGENT ?AGENT0 )
		( CLEAR ?SIDE01 )
		( NOT ( AT-SIDE ?AGENT0 ?SIDE01 ) )
		( AVAILABLE ?AGENT0 )
	)
)
( :ACTION END-LEAVE-TABLE-0
  :PARAMETERS ( ?AGENT0 - AGENT ?SIDE01 - SIDE0 )
  :PRECONDITION
	( AND
		( RESETTING )
		( DONE-AGENT ?AGENT0 )
		( ACTIVE-LEAVE-TABLE-0 ?AGENT0 ?SIDE01 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-AGENT ?AGENT0 ) )
		( FREE-AGENT ?AGENT0 )
		( NOT ( ACTIVE-LEAVE-TABLE-0 ?AGENT0 ?SIDE01 ) )
	)
)
( :ACTION SELECT-MOVE-TABLE-0
  :PARAMETERS ( ?AGENT0 - AGENT ?ROOM1 - ROOM ?ROOM2 - ROOM ?SIDE03 - SIDE0 )
  :PRECONDITION
	( AND
		( SELECTING )
		( FREE-AGENT ?AGENT0 )
		( NOT ( REQ-NEG-MOVE-TABLE-0 ?AGENT0 ?ROOM1 ?ROOM2 ?SIDE03 ) )
		( LIFTING ?AGENT0 ?SIDE03 )
		( INROOM ?AGENT0 ?ROOM1 )
		( CONNECTED ?ROOM1 ?ROOM2 )
	)
  :EFFECT
	( AND
		( NOT ( FREE-AGENT ?AGENT0 ) )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-MOVE-TABLE-0 ?AGENT0 ?ROOM1 ?ROOM2 ?SIDE03 )
	)
)
( :ACTION DO-MOVE-TABLE-0
  :PARAMETERS ( ?AGENT0 - AGENT ?ROOM1 - ROOM ?ROOM2 - ROOM ?SIDE03 - SIDE0 )
  :PRECONDITION
	( AND
		( APPLYING )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-MOVE-TABLE-0 ?AGENT0 ?ROOM1 ?ROOM2 ?SIDE03 )
		( EXISTS
			( ?AGENT4 - AGENT ?SIDE05 - SIDE0 )
			( AND
				( NOT ( = ?SIDE03 ?SIDE05 ) )
				( ACTIVE-MOVE-TABLE-0 ?AGENT4 ?ROOM1 ?ROOM2 ?SIDE05 )
			)
		)
	)
  :EFFECT
	( AND
		( NOT ( BUSY-AGENT ?AGENT0 ) )
		( DONE-AGENT ?AGENT0 )
		( NOT ( INROOM ?AGENT0 ?ROOM1 ) )
		( NOT ( INROOM TABLE0 ?ROOM1 ) )
		( INROOM ?AGENT0 ?ROOM2 )
		( INROOM TABLE0 ?ROOM2 )
	)
)
( :ACTION END-MOVE-TABLE-0
  :PARAMETERS ( ?AGENT0 - AGENT ?ROOM1 - ROOM ?ROOM2 - ROOM ?SIDE03 - SIDE0 )
  :PRECONDITION
	( AND
		( RESETTING )
		( DONE-AGENT ?AGENT0 )
		( ACTIVE-MOVE-TABLE-0 ?AGENT0 ?ROOM1 ?ROOM2 ?SIDE03 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-AGENT ?AGENT0 ) )
		( FREE-AGENT ?AGENT0 )
		( NOT ( ACTIVE-MOVE-TABLE-0 ?AGENT0 ?ROOM1 ?ROOM2 ?SIDE03 ) )
	)
)
( :ACTION SELECT-LIFT-SIDE-0
  :PARAMETERS ( ?AGENT0 - AGENT ?SIDE01 - SIDE0 )
  :PRECONDITION
	( AND
		( SELECTING )
		( FREE-AGENT ?AGENT0 )
		( NOT ( REQ-NEG-LIFT-SIDE-0 ?AGENT0 ?SIDE01 ) )
		( DOWN ?SIDE01 )
		( AT-SIDE ?AGENT0 ?SIDE01 )
		( HANDEMPTY ?AGENT0 )
		( FORALL
			( ?AGENT2 - AGENT ?SIDE03 - SIDE0 )
			( AND
				( NOT ( ACTIVE-LOWER-SIDE-0 ?AGENT2 ?SIDE03 ) )
			)
		)
	)
  :EFFECT
	( AND
		( NOT ( FREE-AGENT ?AGENT0 ) )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-LIFT-SIDE-0 ?AGENT0 ?SIDE01 )
		( FORALL
			( ?AGENT2 - AGENT ?SIDE03 - SIDE0 )
			( AND
				( REQ-NEG-LOWER-SIDE-0 ?AGENT2 ?SIDE03 )
			)
		)
	)
)
( :ACTION DO-LIFT-SIDE-0
  :PARAMETERS ( ?AGENT0 - AGENT ?SIDE01 - SIDE0 )
  :PRECONDITION
	( AND
		( APPLYING )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-LIFT-SIDE-0 ?AGENT0 ?SIDE01 )
	)
  :EFFECT
	( AND
		( NOT ( BUSY-AGENT ?AGENT0 ) )
		( DONE-AGENT ?AGENT0 )
		( NOT ( DOWN ?SIDE01 ) )
		( UP ?SIDE01 )
		( LIFTING ?AGENT0 ?SIDE01 )
		( NOT ( HANDEMPTY ?AGENT0 ) )
		( FORALL
			( ?BLOCK2 - BLOCK ?ROOM3 - ROOM ?SIDE04 - SIDE0 )
			( WHEN
				( AND
					( INROOM TABLE0 ?ROOM3 )
					( ON-TABLE ?BLOCK2 TABLE0 )
					( DOWN ?SIDE04 )
					( FORALL
						( ?AGENT5 - AGENT )
						( NOT ( ACTIVE-LIFT-SIDE-0 ?AGENT5 ?SIDE04 ) )
					)
				)
				( AND
					( ON-FLOOR ?BLOCK2 )
					( INROOM ?BLOCK2 ?ROOM3 )
					( NOT ( ON-TABLE ?BLOCK2 TABLE0 ) )
				)
			)
		)
	)
)
( :ACTION END-LIFT-SIDE-0
  :PARAMETERS ( ?AGENT0 - AGENT ?SIDE01 - SIDE0 )
  :PRECONDITION
	( AND
		( RESETTING )
		( DONE-AGENT ?AGENT0 )
		( ACTIVE-LIFT-SIDE-0 ?AGENT0 ?SIDE01 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-AGENT ?AGENT0 ) )
		( FREE-AGENT ?AGENT0 )
		( NOT ( ACTIVE-LIFT-SIDE-0 ?AGENT0 ?SIDE01 ) )
		( FORALL
			( ?AGENT2 - AGENT ?SIDE03 - SIDE0 )
			( AND
				( NOT ( REQ-NEG-LOWER-SIDE-0 ?AGENT2 ?SIDE03 ) )
			)
		)
	)
)
( :ACTION SELECT-LOWER-SIDE-0
  :PARAMETERS ( ?AGENT0 - AGENT ?SIDE01 - SIDE0 )
  :PRECONDITION
	( AND
		( SELECTING )
		( FREE-AGENT ?AGENT0 )
		( NOT ( REQ-NEG-LOWER-SIDE-0 ?AGENT0 ?SIDE01 ) )
		( LIFTING ?AGENT0 ?SIDE01 )
		( FORALL
			( ?AGENT2 - AGENT ?SIDE03 - SIDE0 )
			( AND
				( NOT ( ACTIVE-LIFT-SIDE-0 ?AGENT2 ?SIDE03 ) )
			)
		)
	)
  :EFFECT
	( AND
		( NOT ( FREE-AGENT ?AGENT0 ) )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-LOWER-SIDE-0 ?AGENT0 ?SIDE01 )
		( FORALL
			( ?AGENT2 - AGENT ?SIDE03 - SIDE0 )
			( AND
				( REQ-NEG-LIFT-SIDE-0 ?AGENT2 ?SIDE03 )
			)
		)
	)
)
( :ACTION DO-LOWER-SIDE-0
  :PARAMETERS ( ?AGENT0 - AGENT ?SIDE01 - SIDE0 )
  :PRECONDITION
	( AND
		( APPLYING )
		( BUSY-AGENT ?AGENT0 )
		( ACTIVE-LOWER-SIDE-0 ?AGENT0 ?SIDE01 )
	)
  :EFFECT
	( AND
		( NOT ( BUSY-AGENT ?AGENT0 ) )
		( DONE-AGENT ?AGENT0 )
		( DOWN ?SIDE01 )
		( NOT ( UP ?SIDE01 ) )
		( NOT ( LIFTING ?AGENT0 ?SIDE01 ) )
		( HANDEMPTY ?AGENT0 )
		( FORALL
			( ?BLOCK2 - BLOCK ?ROOM3 - ROOM ?SIDE04 - SIDE0 )
			( WHEN
				( AND
					( INROOM TABLE0 ?ROOM3 )
					( ON-TABLE ?BLOCK2 TABLE0 )
					( UP ?SIDE04 )
					( FORALL
						( ?AGENT5 - AGENT )
						( NOT ( ACTIVE-LOWER-SIDE-0 ?AGENT5 ?SIDE04 ) )
					)
				)
				( AND
					( ON-FLOOR ?BLOCK2 )
					( INROOM ?BLOCK2 ?ROOM3 )
					( NOT ( ON-TABLE ?BLOCK2 TABLE0 ) )
				)
			)
		)
	)
)
( :ACTION END-LOWER-SIDE-0
  :PARAMETERS ( ?AGENT0 - AGENT ?SIDE01 - SIDE0 )
  :PRECONDITION
	( AND
		( RESETTING )
		( DONE-AGENT ?AGENT0 )
		( ACTIVE-LOWER-SIDE-0 ?AGENT0 ?SIDE01 )
	)
  :EFFECT
	( AND
		( NOT ( DONE-AGENT ?AGENT0 ) )
		( FREE-AGENT ?AGENT0 )
		( NOT ( ACTIVE-LOWER-SIDE-0 ?AGENT0 ?SIDE01 ) )
		( FORALL
			( ?AGENT2 - AGENT ?SIDE03 - SIDE0 )
			( AND
				( NOT ( REQ-NEG-LIFT-SIDE-0 ?AGENT2 ?SIDE03 ) )
			)
		)
	)
)
)
